-- PUNTO 7.3 - COMPARACION CON PYSPARK

-- 1. CREACION DE LA BASE DE DATOS

CREATE DATABASE COMERCIAL_VIDA_SPARK;
GO

USE COMERCIAL_VIDA_SPARK;
GO


-- 2. CREACION DE LA TABLA VENTAS

CREATE TABLE ventas (
    IdVenta INT PRIMARY KEY,
    Fecha DATE,
    IdCliente VARCHAR(20),
    TotalVenta DECIMAL(10,2)
);
GO


-- 3. VERIFICACION DE LOS DATOS IMPORTADOS

SELECT * FROM ventas;


-- 4. VERIFICACION DEL VOLUMEN DE DATOS

SELECT COUNT(*) AS CantidadRegistros
FROM ventas;


-- 5. ACTIVAR MEDICION DEL TIEMPO DE EJECUCION

SET STATISTICS TIME ON;


-- 6. CONSULTA PARA COMPARAR CON PYSPARK

SELECT
    COUNT(IdVenta) AS CantidadVentas,
    ROUND(SUM(TotalVenta), 2) AS TotalVendido,
    ROUND(AVG(TotalVenta), 2) AS PromedioVenta,
    MIN(TotalVenta) AS VentaMinima,
    MAX(TotalVenta) AS VentaMaxima
FROM ventas;


-- 7. DESACTIVAR MEDICION DEL TIEMPO

SET STATISTICS TIME OFF;